# Generated by Django 3.0.6 on 2021-01-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20201115_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='org',
            name='logo',
        ),
    ]
