version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./volm:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - test.env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - test.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: