# Generated by Django 3.0.6 on 2020-11-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
