# Generated by Django 3.0.6 on 2021-01-10 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0006_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users contact info'),
            preserve_default=False,
        ),
    ]
