# Generated by Django 3.0.6 on 2021-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contactinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='line_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
