# Generated by Django 3.0.6 on 2020-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20201210_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='tags',
            field=models.ManyToManyField(help_text='Worker skill identifiers', related_name='tags', to='workers.WorkerTags'),
        ),
    ]
