# Generated by Django 3.0.6 on 2020-12-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_worker_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='title',
            field=models.CharField(default='', help_text='Short title', max_length=100),
            preserve_default=False,
        ),
    ]
