# Generated by Django 3.0.6 on 2020-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_worker_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Day')),
                ('time_from', models.CharField(max_length=50, verbose_name='Time from')),
                ('time_to', models.CharField(max_length=50, verbose_name='Time to')),
                ('timezone', models.CharField(max_length=50, verbose_name='Timezone')),
                ('worker', models.ManyToManyField(to='workers.Worker', verbose_name='workers')),
            ],
        ),
    ]
