# Generated by Django 3.0.6 on 2020-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('workers', '0006_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.ManyToManyField(to='utils.Day', verbose_name='Day'),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='time_from',
        ),
        migrations.AddField(
            model_name='availability',
            name='time_from',
            field=models.ManyToManyField(related_name='time_from', to='utils.Time', verbose_name='Time from'),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='time_to',
        ),
        migrations.AddField(
            model_name='availability',
            name='time_to',
            field=models.ManyToManyField(related_name='time_to', to='utils.Time', verbose_name='Time to'),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='timezone',
        ),
        migrations.AddField(
            model_name='availability',
            name='timezone',
            field=models.ManyToManyField(to='utils.Timezone', verbose_name='Timezone'),
        ),
    ]
