# Generated by Django 3.1.5 on 2021-01-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_auto_20210121_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='orgs',
        ),
    ]
