# Generated by Django 3.1.5 on 2021-01-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_auto_20210121_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
