# Generated by Django 3.1.5 on 2021-01-22 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
        ('workers', '0013_delete_jobtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='AvailabilityDetail',
        ),
        migrations.AlterModelOptions(
            name='availabilitydetail',
            options={'verbose_name_plural': 'Availability in detail'},
        ),
        migrations.CreateModel(
            name='AvailabilityBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(verbose_name='Hours available')),
                ('type', models.CharField(choices=[('wk', 'Week')], max_length=50, verbose_name='Type of availability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Availability as basic',
            },
        ),
    ]
