# Generated by Django 3.1.5 on 2021-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_auto_20210122_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitybasic',
            name='hours',
            field=models.PositiveSmallIntegerField(verbose_name='Hours available'),
        ),
        migrations.AlterField(
            model_name='availabilitybasic',
            name='type',
            field=models.CharField(choices=[('wk', 'Week'), ('mo', 'Month')], max_length=50, verbose_name='Type of availability'),
        ),
    ]
