# Generated by Django 3.1.5 on 2021-01-24 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_auto_20210122_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitybasic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilitybasic',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='availabilitybasic',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Workers advert'),
            preserve_default=False,
        ),
    ]
