# Generated by Django 3.1.5 on 2021-01-25 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0016_auto_20210124_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('length', models.CharField(choices=[('0', '0-1 year'), ('1', '1-3 years'), ('2', '3-6 years'), ('3', '6-12 years'), ('4', '12+ years')], max_length=50, verbose_name='Length of experience')),
                ('main_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workertags', verbose_name='Main skill')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
