# Generated by Django 3.1.5 on 2021-01-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Workers advert'),
            preserve_default=False,
        ),
    ]
